# Summary: TFQ continuous integration workflow for building & testing TFQ.
#
# This workflow compiles TFQ and runs test cases to verify everything works.
# It triggers on certain events such as pull requests and merge-queue merges,
# tries to be as efficient as possible by caching the Python environment and
# Bazel artifacts, and can be invoked manually via the "Run workflow" button at
# https://github.com/tensorflow/quantum/actions/workflows/ci-build-checks.yaml
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: CI build checks
run-name: Continuous integration build & test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

  merge_group:
    types:
      - checks_requested

  push:
    branches:
      - main

  # Allow manual invocation, with options that can be useful for debugging.
  workflow_dispatch:
    inputs:
      sha:
        description: "Commit hash:"
        type: string
        required: true

      py_version:
        description: "Python version:"
        type: string
        default: "3.10.15"

      reload_python_caches:
        description: "Force-reload the Python caches"
        type: boolean
        default: false

      debug:
        description: "Print additional workflow info"
        type: boolean
        default: false

env:
  # Default Python version to use. Important: give it a full x.y.z number.
  py_version: '3.10.15'

  # Additional .bazelrc options to use.
  bazelrc_additions: |
    common -c opt
    common --announce_rc
    common --color=no
    common --experimental_repo_remote_exec
    common --remote_upload_local_results=false
    common --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1"
    common --cxxopt="-std=c++17"
    common --cxxopt="-msse2"
    common --cxxopt="-msse3"
    common --cxxopt="-msse4"
    build --verbose_failures
    test --test_output=errors
    test --test_timeout=1000

  # Note: these regexes are Bash regex syntax, NOT path glob syntax.
  ignore_patterns: |-
    - .*\.md$
    - .*\.jpg$
    - .*\.png$
    - ^\.gitignore
    - ^\.pylintrc
    - ^\.yamllint.yaml
    - ^\.github/problem-matchers/.*
    - ^benchmarks/.*

concurrency:
  # Cancel any previously-started but still active runs on the same branch.
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  inspection:
    runs-on: ubuntu-24.04
    outputs:
      need_run: >-
        ${{steps.check_event.outputs.need_run == 'true'}} ||
        ${{steps.check_files.outputs.need_run == 'true'}}
    steps:
      - if: github.event_name == 'merge_queue'
        id: check_event
        run: |
          echo "need_run=true" >> "$GITHUB_OUTPUT"

      - if: github.event_name != 'merge_queue'
        name: Determine files changed by this ${{github.event_name}}
        id: check_files
        env:
          GH_TOKEN: ${{github.token}}
        # Note that this approach doesn't need to check out a copy of the repo.
        run: |
          set -x
          # Get an array of paths changed in this workflow trigger event.
          event="${{github.event_name}}"
          if [[ "$event" == "pull_request" ]]; then
            pr_url=${{github.event.pull_request.url}}
            read -r -a paths <<< \
              "$(gh pr view $pr_url --json files --jq '.files | .[].path')"
          else
            if [[ "$event" == "push" ]]; then
              sha=${{github.sha}}
            else
              # There's no event sha for manual runs, so we rely on user input.
              sha=${{inputs.sha}}
            fi
            commits_url="/repos/${{github.repository}}/commits/$sha"
            read -r -a paths <<< \
              "$(gh api $commits_url --jq '.files[].filename')"
          fi
          # Test array of paths against the patterns of changes we can ignore.
          echo "need_run=false" >> "$GITHUB_OUTPUT"
          echo "${{env.ignore_patterns}}"
          IFS=$'\n' read -r -d '' -a ignorable <<< ${{env.ignore_patterns}}
          echo "${ignorable[@]}"
          for path in "${paths[@]}"; do
            for pattern in "${ignorable[@]}"; do
              # The path matched a pattern => can be ignored. Go to next path.
              [[ $path =~ $pattern ]] && continue 2
            done
            # None of the patterns matched this path.
            echo "need_run=true" >> "$GITHUB_OUTPUT"
            break
          done
