# Summary: TFQ continuous integration workflow for building & testing TFQ.
#
# This workflow compiles TFQ and runs test cases to verify everything works.
# It triggers on certain events such as pull requests and merge-queue merges,
# tries to be as efficient as possible by caching the Python environment and
# Bazel artifacts, and can be invoked manually via the "Run workflow" button at
# https://github.com/tensorflow/quantum/actions/workflows/ci-build-checks.yaml
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

name: CI build checks
run-name: Continuous integration build & test

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

  merge_group:
    types:
      - checks_requested

  push:
    branches:
      - main

  # Allow manual invocation, with options that can be useful for debugging.
  workflow_dispatch:
    inputs:
      sha:
        description: "SHA of commit to run against:"
        type: string
        required: true

      py_version:
        description: "Python version:"
        type: string
        default: "3.10.15"

      reload_python_caches:
        description: "Force-reload the Python caches"
        type: boolean
        default: false

      debug:
        description: "Print additional workflow info"
        type: boolean
        default: false

env:
  # Default Python version to use. Important: give it a full x.y.z number.
  py_version: '3.10.15'

  # Additional .bazelrc options to use.
  bazelrc_additions: |
    common -c opt
    common --announce_rc
    common --color=no
    common --experimental_repo_remote_exec
    common --remote_upload_local_results=false
    common --cxxopt="-D_GLIBCXX_USE_CXX11_ABI=1"
    common --cxxopt="-std=c++17"
    common --cxxopt="-msse2"
    common --cxxopt="-msse3"
    common --cxxopt="-msse4"
    build --verbose_failures
    test --test_output=errors
    test --test_timeout=1000

  # Note: these regexes are Bash regex syntax, NOT path glob syntax.
  # Also, do not put dashes in front of the values.
  ignore_patterns: |-
    .*\.md$
    .*\.jpg$
    .*\.png$
    ^\.gitignore
    ^\.pylintrc
    ^\.yamllint.yaml
    ^\.github/problem-matchers/.*
    ^benchmarks/.*

concurrency:
  # Cancel any previously-started but still active runs on the same branch.
  cancel-in-progress: true
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}

jobs:
  decision:
    runs-on: ubuntu-24.04
    outputs:
      need_run: >-
        ${{github.event_name == 'merge_queue'}} ||
        ${{steps.files.outputs.have_changes == 'true'}}
    steps:
      - if: github.event_name != 'merge_queue'
        name: Determine files changed by this ${{github.event_name}} event
        id: files
        env:
          GH_TOKEN: ${{github.token}}
        # Note that this approach doesn't need to check out a copy of the repo.
        run: |
          set -x
          # Get an array of paths changed in this workflow trigger event.
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            url=${{github.event.pull_request.url}}
            paths=($(gh pr view $url --json files --jq '.files | .[].path'))
          else
            # There's no event sha for manual runs, so we rely on user input.
            sha=${{github.sha || inputs.sha}}
            url="/repos/${{github.repository}}/commits/$sha"
            paths=($(gh api $url --jq '.files[].filename'))
          fi
          # Test array of paths against the patterns of changes we can ignore.
          # Default to no-changes if every path matches at least one pattern.
          echo "have_changes='false'" >> "$GITHUB_OUTPUT"
          ignorable=(${{env.ignore_patterns}})
          for path in "${paths[@]}"; do
            for pattern in "${ignorable[@]}"; do
              # The path matched a pattern => can be ignored. Go to next path.
              [[ $path =~ $pattern ]] && continue 2
            done
            # None of the patterns matched this path.
            echo "have_changes='true'" >> "$GITHUB_OUTPUT"
            break
          done

  setup:
    if: needs.decision.outputs.need_run == 'true'
    needs: decision
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    outputs:
      python_cache_key: ${{steps.parameters.outputs.python_cache_key}}
      python_cache_paths: ${{steps.parameters.outputs.python_cache_paths}}
      bazel_cache_key: ${{steps.parameters.outputs.bazel_cache_key}}
      debug: ${{steps.parameters.outputs.debug}}
    steps:
      - name: Check out a copy of the TFQ git repository
        uses: actions/checkout@v4

        # Note: setup-python has a cache facility, but we don't use it here
        # because we want to cache more things than setup-python does.
      - name: Set up Python ${{inputs.py_version || env.py_version}}
        id: python
        uses: actions/setup-python@v5
        with:
          python-version: ${{inputs.py_version || env.py_version}}

      - name: Set various parameters
        id: parameters
        run: |
          # Including __init__.py here lets us detect changes to __version__.
          hash=${{hashFiles('WORKSPACE', '**/BUILD', '**/*.bzl', '**/.patch',
                  'requirements.txt', 'tensorflow_quantum/__init__.py')}}
          key="${{github.workflow_ref}}-$hash"
          echo "python_cache_key=$key" >> "$GITHUB_OUTPUT"
          # The paths used for actions/cache need to be on separate lines.
          # shellcheck disable=SC2005
          {
          echo 'python_cache_paths<<EOF'
          echo "$(pip cache dir)"
          echo "${{env.pythonLocation}}"
          echo 'EOF'
          } >> "$GITHUB_OUTPUT"
          # Make the Bazel disk cache specific to the version of this workflow.
          echo "bazel_cache_key=${{github.workflow_ref}}" >> "$GITHUB_OUTPUT"
          # If the user re-runs the workflow with debugging turned on via the
          # GitHub GUI (instead of using workflow_dispatch), include the debug
          # info they'd get if they did use workflow_dispatch.
          if [[ "${{inputs.debug}}" == "true" || "${{runner.debug}}" == "1" ]]; then
            echo "debug=true" >> "$GITHUB_OUTPUT"
          else
            echo "debug=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Test if the cache already exists
        uses: actions/cache@v4
        id: check_cache
        with:
          lookup-only: true
          key: ${{steps.parameters.outputs.python_cache_key}}
          path: ${{steps.parameters.outputs.python_cache_paths}}

      - if: >-
          steps.check_cache.outputs.cache-hit == 'true' &&
          inputs.reload_python_caches == 'true'
        name: Clear the Python cache
        continue-on-error: true
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          key="${{steps.parameters.outputs.python_cache_key}}"
          gh extension install actions/gh-actions-cache
          gh actions-cache delete "$key" --confirm

      - if: >-
          steps.check_cache.outputs.cache-hit != 'true' ||
          inputs.reload_python_caches == 'true'
        name: Set up our Python cache
        uses: actions/cache@v4
        id: restore_cache
        with:
          key: ${{steps.parameters.outputs.python_cache_key}}
          path: ${{steps.parameters.outputs.python_cache_paths}}

      - if: >-
          steps.check_cache.outputs.cache-hit != 'true' ||
          inputs.reload_python_caches == 'true'
        name: Install TFQ Python dependencies and cache them
        run: |
          pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          # The next ones are for validating tutorials
          pip install jupyter
          pip install nbclient==0.6.5 jupyter-client==6.1.12 ipython==7.22.0
          pip install ipykernel==5.1.1
          pip install gym==0.24.1
          pip install seaborn==0.12.0
          pip install -q git+https://github.com/tensorflow/docs
